site_name: Iodine
repo_url: https://github.com/Sintrastes/Iodine
copyright: Copyright &copy; 2020 - 2021 Nathan Bedell
nav:
    - Introduction:  index.md
    - 'Concepts': 
      - concepts/basic_concepts.md
      - concepts/comonadic_components.md
      - concepts/forms_and_profunctors.md
    - 'Examples': 
      - examples/basic_examples.md
      - examples/calculator_app.md
      - examples/todo_app.md
    - 'Additional Resources': 
      - additional/halogen_comparison.md
      - additional/higher_kinds_in_kotlin.md
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - toc.integrate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - markdown.extensions.attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
