# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build core jar
        run: |
            ./gradlew :core:jar
            
      - name: Build desktop jar
        run: |
            ./gradlew :desktop:jar
            
      - name: Build android aar
        run: |
            ./gradlew :android:build

      - name: Build desktop example
        run: |
          cd examples/desktop_example
          ./gradlew build

      - name: Build android example
        run: |
          cd examples/IodineAndroidApp
          ./gradlew build
            
      - name: Archive core jar
        uses: actions/upload-artifact@v2
        with:
          name: core-jar
          path: core/build/libs/iodine-core.jar
          
      - name: Archive desktop jar
        uses: actions/upload-artifact@v2
        with:
          name: desktop-jar
          path: desktop/build/libs/iodine-desktop.jar
          
      - name: Archive android aar
        uses: actions/upload-artifact@v2
        with:
          name: android-aar
          path: android/build/aar/android-debug.aar
