name: DOCS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build dokka docs
        run: |
          ./gradlew dokkaHtmlMultimodule

      - name: Archive dokka docs
        uses: actions/upload-artifact@v2
        with:
          name: iodine-docs
          path: build/dokkaCustomMultiModuleOutput/
